export default {
    GET_POSTS: 'GET_POSTS',
    GET_POST: 'GET_POST',
    SET_POSTS: 'SET_POSTS',
    ADD_POST: 'ADD_POST',
    DELETE_POST: 'DELETE_POST',
    EDIT_POST: 'EDIT_POST',
    SET_READ_POST: 'SET_READ_POST',
    SET_EDIT_POST: 'SET_EDIT_POST'
}